{
  parserClass="com.rythmplugin.parser.RythmParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rythm"
  psiImplClassSuffix="Impl"
  psiPackage="com.rythmplugin.psi"
  psiImplPackage="com.rythmplugin.psi.impl"

  elementTypeHolderClass="com.rythmplugin.psi.RythmTypes"
  elementTypeClass="com.rythmplugin.psi.RythmElementType"
  tokenTypeClass="com.rythmplugin.psi.RythmTokenType"
}

rythmFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY


rythm_Rule ::= rythm_Rule1 rythm_Rule2 rythm_Rule3 rythm_Rule4

rythm_Rule1 ::= AT_FOR
rythm_Rule2 ::= AT_IF
rythm_Rule3 ::= AT_WHILE
rythm_Rule4 ::= AT